Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
asset_list = list(ds.get_assets())
number_assets = len(asset_list)
manifest = pd.DataFrame(columns=('session_id','specimen_id','genotype','area','imaging_depth','sex','age','path','date'), 
                        index=range(number_assets))

def to_struct(asset):
    manifest = {}
    md = asset.get_raw_metadata()
    manifest['session_id'] = md['wasGeneratedBy'][0]['identifier']
    manifest['specimen_id'] = md['wasAttributedTo'][0]['identifier']
    manifest['genotype'] = md['wasAttributedTo'][0]['genotype']
    manifest['sex'] = md['wasAttributedTo'][0]['sex']['name']
    manifest['age'] = md['wasAttributedTo'][0]['age']['value']
    manifest['path'] = md['path']
    manifest['date'] = md['wasGeneratedBy'][0]['startDate']
    
    path = md['path']
    s3_url = asset.get_content_url(regex='s3')
    io = pynwb.NWBHDF5IO(s3_url, mode='r', load_namespaces=True, driver='ros3')
    nwbfile = io.read()
    location = nwbfile.imaging_planes['imaging_plane_1'].location
    manifest['area'] = location.split(',')[0].split((' '))[1]
    manifest['imaging_depth'] = location.split(',')[1].split((' '))[1]
    return manifest

result = Parallel(n_jobs=10)(delayed(to_struct)(asset_list[i]) for i in tqdm(range(number_assets)))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31m_RemoteTraceback[0m                          Traceback (most recent call last)
[0;31m_RemoteTraceback[0m: 
"""
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/tmp/ipykernel_4892/968885907.py", line 19, in to_struct
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/pynwb/__init__.py", line 230, in __init__
    super().load_namespaces(tm, path, file=file_obj, driver=driver)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/utils.py", line 645, in func_call
    return func(args[0], **pargs)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 150, in load_namespaces
    open_file_obj = cls.__resolve_file_obj(path, file_obj, driver)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/hdmf/backends/hdf5/h5tools.py", line 125, in __resolve_file_obj
    file_obj = File(path, 'r', **file_kwargs)
  File "/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/h5py/_hl/files.py", line 485, in __init__
    raise ValueError(
ValueError: h5py was built without ROS3 support, can't use ros3 driver
"""

The above exception was the direct cause of the following exception:

[0;31mValueError[0m                                Traceback (most recent call last)
Cell [0;32mIn [6], line 26[0m
[1;32m     23[0m     manifest[[38;5;124m'[39m[38;5;124mimaging_depth[39m[38;5;124m'[39m] [38;5;241m=[39m location[38;5;241m.[39msplit([38;5;124m'[39m[38;5;124m,[39m[38;5;124m'[39m)[[38;5;241m1[39m][38;5;241m.[39msplit(([38;5;124m'[39m[38;5;124m [39m[38;5;124m'[39m))[[38;5;241m1[39m]
[1;32m     24[0m     [38;5;28;01mreturn[39;00m manifest
[0;32m---> 26[0m result [38;5;241m=[39m Parallel(n_jobs[38;5;241m=[39m[38;5;241m10[39m)(delayed(to_struct)(asset_list[i]) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m tqdm([38;5;28mrange[39m(number_assets)))

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/parallel.py:1098[0m, in [0;36mParallel.__call__[0;34m(self, iterable)[0m
[1;32m   1095[0m     [38;5;28mself[39m[38;5;241m.[39m_iterating [38;5;241m=[39m [38;5;28;01mFalse[39;00m
[1;32m   1097[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39m_backend[38;5;241m.[39mretrieval_context():
[0;32m-> 1098[0m     [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mretrieve[49m[43m([49m[43m)[49m
[1;32m   1099[0m [38;5;66;03m# Make sure that we get a last message telling us we are done[39;00m
[1;32m   1100[0m elapsed_time [38;5;241m=[39m time[38;5;241m.[39mtime() [38;5;241m-[39m [38;5;28mself[39m[38;5;241m.[39m_start_time

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/parallel.py:975[0m, in [0;36mParallel.retrieve[0;34m(self)[0m
[1;32m    973[0m [38;5;28;01mtry[39;00m:
[1;32m    974[0m     [38;5;28;01mif[39;00m [38;5;28mgetattr[39m([38;5;28mself[39m[38;5;241m.[39m_backend, [38;5;124m'[39m[38;5;124msupports_timeout[39m[38;5;124m'[39m, [38;5;28;01mFalse[39;00m):
[0;32m--> 975[0m         [38;5;28mself[39m[38;5;241m.[39m_output[38;5;241m.[39mextend([43mjob[49m[38;5;241;43m.[39;49m[43mget[49m[43m([49m[43mtimeout[49m[38;5;241;43m=[39;49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43mtimeout[49m[43m)[49m)
[1;32m    976[0m     [38;5;28;01melse[39;00m:
[1;32m    977[0m         [38;5;28mself[39m[38;5;241m.[39m_output[38;5;241m.[39mextend(job[38;5;241m.[39mget())

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/site-packages/joblib/_parallel_backends.py:567[0m, in [0;36mLokyBackend.wrap_future_result[0;34m(future, timeout)[0m
[1;32m    564[0m [38;5;124;03m"""Wrapper for Future.result to implement the same behaviour as[39;00m
[1;32m    565[0m [38;5;124;03mAsyncResults.get from multiprocessing."""[39;00m
[1;32m    566[0m [38;5;28;01mtry[39;00m:
[0;32m--> 567[0m     [38;5;28;01mreturn[39;00m [43mfuture[49m[38;5;241;43m.[39;49m[43mresult[49m[43m([49m[43mtimeout[49m[38;5;241;43m=[39;49m[43mtimeout[49m[43m)[49m
[1;32m    568[0m [38;5;28;01mexcept[39;00m CfTimeoutError [38;5;28;01mas[39;00m e:
[1;32m    569[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTimeoutError[39;00m [38;5;28;01mfrom[39;00m [38;5;21;01me[39;00m

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/concurrent/futures/_base.py:446[0m, in [0;36mFuture.result[0;34m(self, timeout)[0m
[1;32m    444[0m     [38;5;28;01mraise[39;00m CancelledError()
[1;32m    445[0m [38;5;28;01melif[39;00m [38;5;28mself[39m[38;5;241m.[39m_state [38;5;241m==[39m FINISHED:
[0;32m--> 446[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m__get_result[49m[43m([49m[43m)[49m
[1;32m    447[0m [38;5;28;01melse[39;00m:
[1;32m    448[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTimeoutError[39;00m()

File [0;32m/opt/hostedtoolcache/Python/3.9.14/x64/lib/python3.9/concurrent/futures/_base.py:391[0m, in [0;36mFuture.__get_result[0;34m(self)[0m
[1;32m    389[0m [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception:
[1;32m    390[0m     [38;5;28;01mtry[39;00m:
[0;32m--> 391[0m         [38;5;28;01mraise[39;00m [38;5;28mself[39m[38;5;241m.[39m_exception
[1;32m    392[0m     [38;5;28;01mfinally[39;00m:
[1;32m    393[0m         [38;5;66;03m# Break a reference cycle with the exception in self._exception[39;00m
[1;32m    394[0m         [38;5;28mself[39m [38;5;241m=[39m [38;5;28;01mNone[39;00m

[0;31mValueError[0m: h5py was built without ROS3 support, can't use ros3 driver
ValueError: h5py was built without ROS3 support, can't use ros3 driver

